Parelon/ParelonCore/Controllers/AttachmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ParelonCore.Controllers
{
    public class AttachmentController : Controller
    {
        // GET: Resource
        public ActionResult List()
        {
            return PartialView();
        }

        public ActionResult _AttachmentItem()
        {
            return PartialView();
        }
    }
}

Parelon/ParelonCore/Controllers/BarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ParelonCore.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ParelonCore.Controllers
{
    public class BarsController : Controller
    {
        //public ActionResult TitleBar(string title, string subtitle)
        //{
        //    ViewBag.Title = title;
        //    ViewBag.Subtitle = subtitle;
        //    return PartialView();
        //}

        public ActionResult GoPrev()
        {
            ViewContext prev = History.getPrev();
            if (prev != null)
                return View(prev.View);
            else return null;
        }

        public ActionResult GoNext()
        {
            ViewContext next = History.getNext();
            if(next != null)
                return View(next.View);
            else return null;
        }
        
        //public ActionResult StatusBar()
        //{
        //    return PartialView();
        //}

        //public ActionResult MessagesBar()
        //{
        //    return PartialView();
        //}

        public ActionResult AmendmentBar()
        {
            return PartialView();
        }
    }
}

Parelon/ParelonCore/Controllers/InitiativeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ParelonCore.Controllers
{
    public class InitiativeController : Controller
    {
        public ActionResult Show() { return View(); }
        public ActionResult _Introduction() { return PartialView(); }
        public ActionResult _Draft() { return PartialView(); }
        public ActionResult _Actions() { return PartialView(); }
        public ActionResult _Authors(bool isAnonimous)
        {
            ViewBag.isAnonimous = isAnonimous;
            return PartialView();
        }
        public ActionResult _Policy() { return PartialView(); }
        public ActionResult _Keywords() { return PartialView(); }
        public ActionResult _DetailedData() { return PartialView(); }
        public ActionResult _Supporters(bool isAnonimous)
        {
            ViewBag.isAnonimous = isAnonimous;
            return PartialView();
        }
        public ActionResult _PotentialSupporters(bool isAnonimous)
        {
            ViewBag.isAnonimous = isAnonimous;
            return PartialView();
        }
        public ActionResult _Votes() { return PartialView(); }
        public ActionResult _Population(bool isAnonimous)
        {
            ViewBag.isAnonimous = isAnonimous;
            return PartialView();
        }

        public ActionResult List()
        {
            return PartialView();
        }

        public ActionResult _InitiativeItem()
        {
            return PartialView();
        }
    }
}

Parelon/ParelonCore/Controllers/IssueController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ParelonCore.Controllers
{
    public class IssueController : Controller
    {
        public ActionResult ShowDiscussion ( ) { return View(); }
        public ActionResult ShowAct ( ) { return View(); }
        public ActionResult _Introduction ( ) { return PartialView(); }
        public ActionResult _Actions ( ) { return PartialView(); }
        public ActionResult _Authors ( bool isAnonimous )
        {
            ViewBag.isAnonimous = isAnonimous;
            return PartialView();
        }
        public ActionResult _Initiatives ( ) { return PartialView(); }
        public ActionResult _Policy ( ) { return PartialView(); }
        public ActionResult _Keywords ( ) { return PartialView(); }
        public ActionResult _DetailedData ( ) { return PartialView(); }
        public ActionResult _Supporters ( bool isAnonimous )
        {
            ViewBag.isAnonimous = isAnonimous;
            return PartialView();
        }
        public ActionResult _Population ( bool isAnonimous )
        {
            ViewBag.isAnonimous = isAnonimous;
            return PartialView();
        }

        public ActionResult List ( )
        {
            return View();
        }

        public ActionResult _IssueItem ( )
        {
            return PartialView();
        }
    }
}

Parelon/ParelonCore/Controllers/VoteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ParelonCore.Controllers
{
    public class VoteController : Controller
    {
        public ActionResult VoteNow()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Login", "Account", new { ReturnUrl = "~/Vote/VoteNow" });
            else
                return View();
        }

        public ActionResult _VoteBox ( int initiativeId )
        {
            ViewBag.initiativeId = initiativeId;
            return PartialView();
        }
    }
}

Parelon/ParelonCore/Views/Issue/List.cshtml
@using ParelonCore.ViewComponents

@{
    ViewBag.Title = "Lista problemi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    //Html.RenderAction("TitleBar", "Bars", new { title = "Problemi", subtitle = "Lista dei problemi aperti a cui puoi partecipare" });
    await Component.InvokeAsync(nameof(TitleBar), new { title = "Problemi", subtitle = "Lista dei problemi aperti a cui puoi partecipare" });

}
<div class="row" style="margin-bottom: 0px;">
    <span class="col-xs-12 box-title"><strong>Lista problemi inseriti</strong></span>
</div>
<div class="row well" style="margin-top: 0px">
    <ul class="bs-ul col-xs-12">
        <li>
            <div class="row">
                <a class="col-xs-4 btn btn-primary" href="@Url.Action("ShowDiscussion","Issue")">
                    Problema Dummy 1
                </a>
            </div>
        </li>
        <li>
            <div class="row">
                <a class="col-xs-4 btn btn-success" href="@Url.Action("ShowAct", "Issue")">
                    Atto Dummy 2 <div class="badge">In risposta a Problema Dummy 1</div>
                </a>
            </div>
        </li>
        <li>
            <div class="row">
                <a class="col-xs-4 btn btn-danger" href="@Url.Action("ShowAct", "Issue")">
                    Che ne pensate? <div class="badge">Atto segnalato</div>
                </a>
            </div>
        </li>
        <li>
            <div class="row">
                <a class="col-xs-4 btn btn-primary" href="@Url.Action("ShowDiscussion", "Issue")">
                    Problema Dummy 4
                </a>
            </div>
        </li>
        <li>
            <div class="row">
                <a class="col-xs-4 btn btn-primary" href="@Url.Action("ShowDiscussion", "Issue")">
                    Problema Dummy 5
                </a>
            </div>
        </li>
    </ul>
</div>

Parelon/ParelonCore/Views/Issue/ShowAct.cshtml
@using ParelonCore.Core
@using ParelonCore.ViewComponents

@{
    ViewBag.Title = "Discussione Atto - Problema";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    //Html.RenderAction("TitleBar", "Bars", new { title = "Titolo del problema", subtitle = "Abstract: (max. 180 caratteri) Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam ecc." });
    await Component.InvokeAsync(nameof(TitleBar), new { title = "Titolo del problema", subtitle = "Abstract: (max. 180 caratteri) Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam ecc." });
}
@*Introduction*@
<a name="Introduction"></a>
<div class="row">
    <div class="col-xs-6">
        @Html.Partial("~/Views/Shared/ProgressBar.cshtml")
    </div>
    <div class="col-xs-6">
        <div class="row" style="margin-bottom: 0px;">
            <span class="col-xs-6 box-title"><strong>Social</strong></span>
        </div>
        <div class="row well" style="margin-top: 0px;">
            <div class="col-xs-12">
                <div class="row">
                    <span class="col-xs-12">@Context.Request.Host@Context.Request.Path</span>
                </div>
                <div class="row" style="margin-top: 5px;">
                    <div class="fb-like col-xs-12"
                         data-href="@Context.Request.Host@Context.Request.Path"
                         data-layout="standard"
                         data-action="like"
                         data-show-faces="true">
                        <a class="fb-xfbml-parse-ignore" target="_blank" href="@Context.Request.Host@Context.Request.Path">Condividi</a>
                    </div>
                </div>
                <div class="row" style="margin-top: 5px;">
                    <div class="col-xs-3">
                        <a class="twitter-share-button"
                           href="https://twitter.com/intent/tweet?hashtags=parelon"
                           data-size="default">Tweet</a>
                    </div>
                    <div class="col-xs-3">
                        <div class="g-plusone" data-href="@Context.Request.Host@Context.Request.Path"></div>
                    </div>
                    <div class="col-xs-3">
                        <script type="IN/Share" data-url="@Context.Request.Host@Context.Request.Path" data-counter="right">
                        </script>
                    </div>
                    <div class="col-xs-3">
                        <a href="https://telegram.me/share/url?url=@Context.Request.Host@Context.Request.Path"><img src="~/Content/Images/telegram_share_white.png" /></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@*Initiatives*@
@if (true)
{
    //if there is just one initiative then render the text
    Html.RenderAction("Index", "Document");
}
else
{
    //else show the alternatives
    Html.RenderPartial("_ListInitiatives");
}
@*Attachment*@
@{ Html.RenderAction("List", "Attachment");
}
@*Keywords*@
@{ Html.RenderPartial("_Keywords"); }

@if (false)
{
    //if this is in response to something
    <div class="row" style="margin-bottom: 0px;">
        <span class="col-xs-4 box-title"><strong>In risposta al problema</strong></span>
    </div>
    <div class="row well" style="margin-top: 0px;">
        <div class="col-xs-12">
            <div class="row">
                <a class="col-xs-4 btn btn-primary" href="@Url.Action("Issue", "ShowDiscussion")">
                    Problema Dummy 1
                </a>
            </div>
        </div>
    </div>
}

    @*Author*@
    @*Check privacy settings*@
    @if (Privacy.isAccessible())
    {
        // Check for anonimus discussion
        Html.RenderPartial("_Authors", new { isAnonimous = Privacy.isAnonimous() });
    }
    @*Actions*@
    @{ Html.RenderPartial("_Actions"); }
    @*Check privacy settings*@
    <a name="Transparency"></a>
    @if (Privacy.isAccessible())
    {
        <div class="row" style="margin-bottom: 0px;">
            <a role="button" class="col-xs-4 btn btn-primary" data-toggle="collapse" data-target="#transparency-data">
                <strong>Mostra area trasparenza</strong>
            </a>
        </div>
        <div class="row transparency-collapse collapse" id="transparency-data" style="margin-top: 0px;">
            <div class="col-xs-12 well">
                <div>
                    @*Policy*@
                    @{ Html.RenderPartial("_Policy"); }
                </div>
                <div>
                    @*Supporters*@
                    @{ Html.RenderPartial("_Supporters", new { isAnonimous = Privacy.isAnonimous() }); }
                </div>
                <div>
                    @*Population*@
                    @{ Html.RenderPartial("_Population", new { isAnonimous = Privacy.isAnonimous() }); }
                </div>
            </div>
        </div>
                        }
                        @*DetailedData*@
                        @{ Html.RenderPartial("_DetailedData"); }

Parelon/ParelonCore/Views/Issue/ShowDiscussion.cshtml
@using ParelonCore.Core
@using ParelonCore.ViewComponents

@{
    ViewBag.Title = "Discussione Generale - Problema";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ 
    //Html.RenderAction("TitleBar", "Bars", new { title = "Titolo del problema", subtitle = "Abstract: (max. 180 caratteri) Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam ecc." });
    await Component.InvokeAsync(nameof(TitleBar), new { title = "Titolo del problema", subtitle = "Abstract: (max. 180 caratteri) Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam ecc." });

    }
@*Introduction*@
@{ Html.RenderPartial("_Introduction"); }
@*Attachment*@
@{ Html.RenderAction("List", "Attachment"); }
@*Keywords*@
@{ Html.RenderPartial("_Keywords"); }
@*Initiatives*@
@{ Html.RenderPartial("_ListInitiatives"); }
@*Author*@
@*Check privacy settings*@
@if (Privacy.isAccessible())
{
    // Check for anonimus discussion
    Html.RenderPartial("_Authors", new { isAnonimous = Privacy.isAnonimous() });
}
@*Actions*@
@{ Html.RenderPartial("_Actions"); }
@*Check privacy settings*@
<a name="Transparency"></a>
@if (Privacy.isAccessible())
{
    <div class="row" style="margin-bottom: 0px;">
        <a role="button" class="col-xs-4 btn btn-primary" data-toggle="collapse" data-target=".transparency-collapse">
            <strong>Mostra area trasparenza</strong>
        </a>
    </div>
    <div class="row transparency-collapse collapse" style="margin-top: 0px;">
        <div class="col-xs-12 well">
            <div>
                @*Policy*@
                @{ Html.RenderPartial("_Policy"); }
            </div>
            <div>
                @*Supporters*@
                @{ Html.RenderPartial("_Supporters", new { isAnonimous = Privacy.isAnonimous() }); }
            </div>
            <div>
                @*Population*@
                @{ Html.RenderPartial("_Population", new { isAnonimous = Privacy.isAnonimous() }); }
            </div>
        </div>
    </div>
                    }
                    @*DetailedData*@
                    @{ Html.RenderPartial("_DetailedData"); }

Parelon/ParelonCore/Views/Issue/_Actions.cshtml
<div class="panel-group actions" id="accordion" role="tablist" aria-multiselectable="false">
    <div class="panel panel-primary">
        <div class="panel-heading" role="tab" id="headingOne">
            <div class="row">
                <span class="box-title"><strong>Azioni Possibili</strong></span>
                <a role="button" class="pull-right btn btn-default" data-toggle="collapse" data-parent="#accordion" href="#actionsMenu" aria-expanded="true" aria-controls="collapseOne">
                    Mostra/Nascondi
                </a>
            </div>
        </div>
        <div id="actionsMenu" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
                <ul class="bs-ul bs-ul-actions">
                    @if (Request.IsAuthenticated)
                    {
                        <li><a class="btn btn-info"><div class="glyphicon glyphicon-thumbs-up"></div> Sostieni</a></li>
                        <li><a class="btn btn-info"><div class="glyphicon glyphicon-volume-off"></div>Disattiva aggiornamenti da questo problema</a></li>
                        <li><a class="btn btn-info" href="~/Wizard/AddInitiative"><div class="glyphicon glyphicon-edit"></div>Proponi una soluzione per questo problema</a></li>
                        <li>@Html.ActionLink("Vota", "VoteNow", "Vote", routeValues: null, htmlAttributes: new { @class = "btn btn-success" })</li>
                        <li class="divider"></li>
                    }
                    <li class="li-actions"><a class="btn btn-default" href="#Introduction">Mostra l'introduzione</a></li>
                    <li class="li-actions"><a class="btn btn-default" href="#Attachment">Mostra gli allegati</a></li>
                    <li class="li-actions"><a class="btn btn-default" href="#Initiatives">Mostra le soluzioni proposte</a></li>
                    <li class="li-actions"><a class="btn btn-default" href="#Transparency">Mostra l'area trasparenza</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

Parelon/ParelonCore/Views/Issue/_Authors.cshtml
@using Parelon.Core;
<a name="Authors"></a>
<div class="row" style="margin-bottom: 0px;">
    <span class="col-xs-4 box-title"><strong>Autori</strong></span>
</div>
<div class="row well" style="margin-top: 0px;">
    <div class="col-xs-12">
        <div class="row">
            @if (!Privacy.isAnonimous())
            {
                <div class="author-box">
                    @for (int i = 0; i < 2; i++)
                    {
                        <div class="author-box-element col-xs-4">
                            <div class="row">
                                <div class="col-xs-4 user-box-avatar">
                                    <div class="glyphicon glyphicon-user"></div>
                                </div>
                                <div class="col-xs-8">
                                    <span>Autore @(i + 1)</span>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
            else
            {
                <span class="col-xs-12"> Per questa discussione è stata chiesta e ottenuta la discussione anonima. Tutti i dati saranno pubblicati alla chiusura della discussione.</span>
            }
        </div>
    </div>
</div>

Parelon/ParelonCore/Views/Issue/_DetailedData.cshtml
<a name="Details"></a>
<div class="row" style="margin-bottom: 0px;">
    <span class="col-xs-4 box-title"><strong>Dettagli</strong></span>
</div>
<div class="row well" style="margin-top: 0px;">
    <div class="col-xs-12">Elenco dettagli</div>
</div>

Parelon/ParelonCore/Views/Issue/_Introduction.cshtml
<a name="Introduction"></a>
<div class="row">
    <div class="col-xs-6">
        @Html.Partial("~/Views/Shared/ProgressBar.cshtml")
    </div>
    <div class="col-xs-6">
        <div class="row" style="margin-bottom: 0px;">
            <span class="col-xs-6 box-title"><strong>Social</strong></span>
        </div>
        <div class="row well" style="margin-top: 0px;">
            <div class="col-xs-12">
                <div class="row">
                    <span class="col-xs-12">@Context.Request.Host@Context.Request.Path</span>
                </div>
                <div class="row" style="margin-top: 5px;">
                    <div class="fb-like col-xs-12"
                         data-href="@Context.Request.Host@Context.Request.Path"
                         data-layout="standard"
                         data-action="like"
                         data-show-faces="true">
                        <a class="fb-xfbml-parse-ignore" target="_blank" href="@Context.Request.Host@Context.Request.Path">Condividi</a>
                    </div>
                </div>
                <div class="row" style="margin-top: 5px;">
                    <div class="col-xs-3">
                        <a class="twitter-share-button"
                           href="https://twitter.com/intent/tweet?hashtags=parelon"
                           data-size="default">Tweet</a>
                    </div>
                    <div class="col-xs-3">
                        <div class="g-plusone" data-href="@Context.Request.Host@Context.Request.Path"></div>
                    </div>
                    <div class="col-xs-3">
                        <script type="IN/Share" data-url="@Context.Request.Host@Context.Request.Path" data-counter="right">
                        </script>
                    </div>
                    <div class="col-xs-3">
                        <a href="https://telegram.me/share/url?url=@Context.Request.Host@Context.Request.Path"><img src="~/Content/Images/telegram_share_white.png" /></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row" style="margin-bottom: 0px;">
    <span class="col-xs-4 box-title"><strong>Descrizione</strong></span>
</div>
<div class="row well" style="margin-top: 0px;">
    <div class="col-xs-12 text-justified">Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
</div>
<div class="row" style="margin-bottom: 0px;">
    <span class="col-xs-4 box-title"><strong>Obiettivo? Da togliere?</strong></span>
</div>
<div class="row well text-justified" style="margin-top: 0px;">
    <div class="col-xs-12">Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
</div>

Parelon/ParelonCore/Views/Issue/_IssueItem.cshtml
<div class="row" style="margin-top: 0px;">
    <div class="col-xs-12">
        @Html.ActionLink("Dummy", "Show", "Issue", routeValues: null, htmlAttributes: null);
    </div>
</div>

Parelon/ParelonCore/Views/Issue/_Keywords.cshtml
<a name="Keywords"></a>
<div class="row" style="margin-bottom: 0px;">
    <span class="col-xs-4 box-title"><strong>Parole chiave</strong></span>
</div>
<div class="row well" style="margin-top: 0px;">
    <div class="col-xs-12">Elenco parole chiave</div>
</div>

Parelon/ParelonCore/Views/Issue/_ListInitiatives.cshtml
<a name="Initiatives"></a>
<div class="row" style="margin-bottom: 0px;">
    <span class="col-xs-12 box-title"><strong>Lista soluzioni proposte</strong></span>
</div>
<div class="row well" style="margin-top: 0px;">
    <ul class="col-xs-12 bs-ul">
        <li>
            <div class="row">
                <a class="btn btn-default col-xs-4" href="@Url.Action("Show", "Initiative")">
                    <div class="row">
                        <div class="text-center col-xs-7">
                            <strong>Dummy 1</strong>
                            <br/>
                            <span>Nome e Cognome</span>
                        </div>
                        <div id="chart_div_1" class="col-xs-4" style="height: 75px; max-width: 75px;"></div>
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div class="row">
                <a class="btn btn-primary col-xs-4 href="@Url.Action("Show", "Initiative")">
                    <div class="row">
                        <div class="text-center col-xs-7">
                            <strong>Dummy 2</strong>
                            <br />
                            <span>Nome e Cognome</span>
                        </div>
                        <div id="chart_div_2" class="col-xs-4" style="height: 75px; max-width: 75px;"></div>
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div class="row">
                <a class="btn btn-warning col-xs-4" href="@Url.Action("Show", "Initiative")">
                    <div class="row">
                        <div class="text-center col-xs-7">
                            <strong>Dummy 3</strong>
                            <br />
                            <span>Nome e Cognome</span>
                        </div>
                        <div id="chart_div_3" class="col-xs-4" style="height: 75px; max-width: 75px;"></div>
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div class="row">
                <a class="btn btn-info col-xs-4" href="@Url.Action("Show", "Initiative")">
                    <div class="row">
                        <div class="text-center col-xs-7">
                            <strong>Dummy 4</strong>
                            <br />
                            <span>Nome e Cognome</span>
                        </div>
                        <div id="chart_div_4" class="col-xs-4" style="height: 75px; max-width: 75px;"></div>
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div class="row">
                <a class="btn btn-success col-xs-4" href="@Url.Action("Show", "Initiative")">
                    <div class="row">
                        <div class="text-center col-xs-7">
                            <strong>Dummy 5</strong>
                            <br />
                            <span>Nome e Cognome</span>
                        </div>
                        <div id="chart_div_5" class="col-xs-4" style="height: 75px; max-width: 75px;"></div>
                    </div>
                </a>
            </div>
        </li>
        <li>
            <div class="row">
                <a class="btn btn-danger col-xs-4" href="@Url.Action("Show", "Initiative")">
                    <div class="row">
                        <div class="text-center col-xs-7">
                            <strong>Dummy 6</strong>
                            <br />
                            <span>Nome e Cognome</span>
                        </div>
                        <div id="chart_div_6" class="col-xs-4" style="height: 75px; max-width: 75px;"></div>
                    </div>
                </a>
            </div>
        </li>
    </ul>
</div>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
    google.charts.load('current', { 'packages': ['gauge'] });
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Support', 80],
        ]);

        var options = {
            width: 75, height: 75,
            redFrom: 0, redTo: 50,
            yellowFrom: 50, yellowTo: 75,
            greenFrom: 75, greenTo: 100,
            minorTicks: 5
        };

        var chart1 = new google.visualization.Gauge(document.getElementById('chart_div_1'));
        chart1.draw(data, options);
        data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
        var chart2 = new google.visualization.Gauge(document.getElementById('chart_div_2'));
        chart2.draw(data, options);
        data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
        var chart3 = new google.visualization.Gauge(document.getElementById('chart_div_3'));
        chart3.draw(data, options);
        data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
        var chart4 = new google.visualization.Gauge(document.getElementById('chart_div_4'));
        chart4.draw(data, options);
        data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
        var chart5 = new google.visualization.Gauge(document.getElementById('chart_div_5'));
        chart5.draw(data, options);
        data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
        var chart6 = new google.visualization.Gauge(document.getElementById('chart_div_6'));
        chart6.draw(data, options);

        setInterval(function () {
            data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
            chart1.draw(data, options);
            data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
            chart2.draw(data, options);
            data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
            chart3.draw(data, options);
            data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
            chart4.draw(data, options);
            data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
            chart5.draw(data, options);
            data.setValue(0, 1, 40 + Math.round(60 * Math.random()));
            chart6.draw(data, options);
        }, 1000);
    }
</script>

Parelon/ParelonCore/Views/Issue/_Policy.cshtml
<a name="Policy"></a>
<div class="row" style="margin-bottom: 0px;">
    <span class="col-xs-4 box-title"><strong>Politiche di discussione</strong></span>
</div>
<div class="row well" style="margin-top: 0px;">
    <div class="col-xs-12">Dettaglio politiche</div>
</div>