Parelon/ParelonCore/Controllers/BarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ParelonCore.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ParelonCore.Controllers
{
    public class BarsController : Controller
    {
        //public ActionResult TitleBar(string title, string subtitle)
        //{
        //    ViewBag.Title = title;
        //    ViewBag.Subtitle = subtitle;
        //    return PartialView();
        //}

        public ActionResult GoPrev()
        {
            ViewContext prev = History.getPrev();
            if (prev != null)
                return View(prev.View);
            else return null;
        }

        public ActionResult GoNext()
        {
            ViewContext next = History.getNext();
            if(next != null)
                return View(next.View);
            else return null;
        }
        
        //public ActionResult StatusBar()
        //{
        //    return PartialView();
        //}

        //public ActionResult MessagesBar()
        //{
        //    return PartialView();
        //}

        public ActionResult AmendmentBar()
        {
            return PartialView();
        }
    }
}

Parelon/ParelonCore/Controllers/TerritoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ParelonCore.Controllers
{
    public class TerritoryController : Controller
    {
        // GET: Territory
        public ActionResult List()
        {
            return View();
        }

        public ActionResult _TerritoryItem()
        {
            return PartialView();
        }
    }
}

Parelon/ParelonCore/Controllers/TopicController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ParelonCore.Controllers
{
    public class TopicController : Controller
    {
        // GET: TopicController
        public ActionResult List()
        {
            return View();
        }

        public ActionResult _TopicItem()
        {
            return PartialView();
        }
    }
}

Parelon/ParelonCore/Views/Territory/List.cshtml
@using ParelonCore.ViewComponents

@{
    ViewBag.Title = "Lista territori";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ 
    //Html.RenderAction("TitleBar", "Bars", new { title = "Territori", subtitle = "Lista dei territori a cui puoi accedere." });
    await Component.InvokeAsync(nameof(TitleBar), new { title = "Territori", subtitle = "Lista dei territori a cui puoi accedere." });
    }

<div class="row" style="margin-bottom: 0px;">
    <span class="col-xs-12 box-title"><strong>Lista territori abilitati</strong></span>
</div>
<div class="row well" style="margin-top: 0px">
    <ul class="bs-ul col-xs-12">
        <li><div class="row">@Html.ActionLink("Territorio Dummy", "List", "Topic", routeValues: null, htmlAttributes: new { @class = "btn btn-primary col-xs-4" })</div></li>
    </ul>
</div>

Parelon/ParelonCore/Views/Territory/_TerritoryItem.cshtml
<div class="row">
    <div class="col-xs-12">
        @Html.ActionLink("Dummy", "List", "Topic", routeValues: null, htmlAttributes: null);
    </div>
</div>